version: '3.9'

services:
  postgres:
    image: postgres:latest
    container_name: pg_danit
    restart: always
    environment:
      POSTGRES_USER: app0
      POSTGRES_PASSWORD: pg12345
      POSTGRES_DB: app_danit
    volumes:
      - ./.data:/var/lib/postgresql/data
    ports:
      - "5432:5432"